[tool.mypy]
files = "**/*.py"
exclude = [
    ".git",
    "__pycache__",
    ".ruff_cache",
    ".pytest_cache",
    ".import_linter_cache",
    "fabfile.py",
    "fab_utils.py",
    "**/alembic/**",
]

[[tool.mypy.overrides]]
module = [
    'IPython.*',
    'aioboto3.*',
    'apscheduler.*',
    'fabric.*',
    'msgpack.*',
    'aiokafka.*',
    'cryptography.*',
    'sniffio.*',
    'pkg_resources.*',
]
ignore_missing_imports = true
